In [1]:
import sys

import tensorflow
from tensorflow import keras
import pandas as pd
import sklearn as sk
import scipy as sp
import tensorflow as tf
import platform

print(f"Python Platform: {platform.platform()}")
print(f"Tensor Flow Version: {tf.__version__}")
# print(f"Keras Version: {tf.keras.__version__}")
print()
print(f"Python {sys.version}")
print(f"Pandas {pd.__version__}")
print(f"Scikit-Learn {sk.__version__}")
print(f"SciPy {sp.__version__}")
gpu = len(tf.config.list_physical_devices('GPU'))>0
print("GPU is", "available" if gpu else "NOT AVAILABLE")

Python Platform: macOS-14.4.1-arm64-arm-64bit
Tensor Flow Version: 2.16.1

Python 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:35:41) 
[Clang 16.0.6 ]
Pandas 2.2.1
Scikit-Learn 1.4.2
SciPy 1.13.0
GPU is available


In [2]:
!pip install gym-xiangqi

In [84]:
# import gymnasium as gym
from gym_xiangqi.constants import RED, BLACK, PIECE_ID_TO_NAME, ALLY
from gym_xiangqi.utils import action_space_to_move
from gym_xiangqi.agents import RandomAgent


import random
import time 
import numpy as np
import flappy_bird_gymnasium
import gymnasium
import torch

from collections import deque
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import load_model, save_model, Sequential
# from tensorflow.keras.optimizers.legacy import RMSprop      #Runs faster for M1/M2 macs. Use the line below for any other system
from tensorflow.keras.optimizers import RMSprop

In [78]:
import gym
import time

env = gym.make('gym_xiangqi:xiangqi-v0')
env.reset()

# done = False
# while not done:
#     time.sleep(1)
#     # env.render()
#     action = env.action_space.sample()
#     obs, reward, done, info = env.step(action)
# env.close()

/opt/miniconda3/envs/py39/lib/python3.9/site-packages/gym/utils/passive_env_checker.py:31: UserWarning: WARN: A Box observation space has an unconventional shape (neither an image, nor a 1D vector). We recommend flattening the observation to have only a 1D vector or use a custom policy to properly process the data. Actual observation shape: (10, 9)
  logger.warn(
/opt/miniconda3/envs/py39/lib/python3.9/site-packages/gym/utils/passive_env_checker.py:174: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.warn(
/opt/miniconda3/envs/py39/lib/python3.9/site-packages/gym/utils/passive_env_checker.py:187: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.warn(
/opt/miniconda3/envs/py39/lib/python3.9/site-packages/gym/utils/passive_env

array([[ -9,  -7,  -5,  -3,  -1,  -2,  -4,  -6,  -8],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, -11,   0,   0,   0,   0,   0, -10,   0],
       [-16,   0, -15,   0, -14,   0, -13,   0, -12],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 12,   0,  13,   0,  14,   0,  15,   0,  16],
       [  0,  10,   0,   0,   0,   0,   0,  11,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  8,   6,   4,   2,   1,   3,   5,   7,   9]])

In [79]:
num_actions = env.action_space.n
num_observations = env.observation_space.shape[0]  
print(f"There are {num_actions} possible actions and {num_observations} observations")

There are 129600 possible actions and 10 observations


In [80]:
env.action_space


Discrete(129600)

In [81]:
from collections import defaultdict

observation= env.reset()
print(observation)
q_values = defaultdict(lambda: np.zeros(env.action_space.n))

print(env.action_space.n)

[[ -9  -7  -5  -3  -1  -2  -4  -6  -8]
 [  0   0   0   0   0   0   0   0   0]
 [  0 -11   0   0   0   0   0 -10   0]
 [-16   0 -15   0 -14   0 -13   0 -12]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [ 12   0  13   0  14   0  15   0  16]
 [  0  10   0   0   0   0   0  11   0]
 [  0   0   0   0   0   0   0   0   0]
 [  8   6   4   2   1   3   5   7   9]]
129600


In [82]:
action = env.action_space.sample()
print(action)

84776


In [83]:
env = gym.make('gym_xiangqi:xiangqi-v0')
env.reset()
# env.render()
agent = RandomAgent()

done = False
round = 0
    
while not done:
    # if env.turn == ALLY:
    #     obs, reward, done, info = env.step_user()

    #     if "exit" in info and info["exit"]:
    #         break

    #     player = "You"
    #     piece, start, end = env.user_move_info
    #     piece = PIECE_ID_TO_NAME[piece]
    # else:
    time.sleep(1)
    action = env.action_space.sample()
    obs, reward, done, info = env.step(action)

    player = "RL Agent"
    move = action_space_to_move(action)
    piece = PIECE_ID_TO_NAME[move[0]]
    start = move[1]
    end = move[2]

    # env.render()
    round += 1
    print(f"Round: {round}")
    print(f"{player} made the move {piece} from {start} to {end}.")
    print(f"Reward: {reward}")
    print("================")
env.close()

/opt/miniconda3/envs/py39/lib/python3.9/site-packages/gym/utils/passive_env_checker.py:219: DeprecationWarning: WARN: Core environment is written in old step API which returns one bool instead of two. It is recommended to rewrite the environment with new step API. 
  logger.deprecation(
/opt/miniconda3/envs/py39/lib/python3.9/site-packages/gym/utils/passive_env_checker.py:225: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(done, (bool, np.bool8)):


Round: 1
RL Agent made the move SOLDIER_2 from [7, 3] to [1, 6].
Reward: -10.0
Round: 2
RL Agent made the move ELEPHANT_2 from [9, 3] to [9, 2].
Reward: -10.0
Round: 3
RL Agent made the move CANNON_1 from [4, 1] to [2, 7].
Reward: -10.0
Round: 4
RL Agent made the move SOLDIER_5 from [7, 0] to [3, 6].
Reward: -10.0


KeyboardInterrupt: 

In [55]:
import gymnasium as gym
from tqdm import tqdm

# from llamagym import Agent

In [ ]:
class XiangQiAgent(RandomAgent):
    def get_system_prompt(self) -> str:
        return """"You are a skilled Xiangqi player. Each turn, you'll observe the current board state, including the positions of your pieces and the opponent's pieces, as well as the status of your general and the opponent's general. The game objective is to checkmate the opponent's general while safeguarding your own.
                Decide your next move by providing an action code:
                "Action: 0" to maintain your current position and strategy.
                "Action: 1" to make a move or capture an opponent's piece.
                Prioritize capturing opponent pieces when strategically advantageous. Protect your general and establish control over key points on the board. Utilize tactics such as pinning, forking, and skewering to gain an advantage.

                End the game by checkmating the opponent's general or securing a favorable position. Avoid reckless moves that expose your general to immediate threats.
                Adapt your strategy based on the opponent's moves and board developments. Continuously assess the board and adjust your tactics accordingly.
                By following these guidelines, aim to outmaneuver your opponent and achieve victory in the game of Xiangqi."""

    def format_observation(self, observation: gym.core.ObsType) -> str:
        return f"You: {observation[0]}. Dealer: {observation[1]}. You have {'an' if bool(observation[2]) else 'no'} ace."

    def extract_action(self, response: str) -> gym.core.ActType:
        match = re.compile(r"Action: (\d)").search(response)
        if match:
            return int(match.group(1))

        digits = [char for char in response if char.isdigit()]
        if len(digits) == 0 or digits[-1] not in ("0", "1"):
            if "stick" in response.lower():
                return 0
            elif "hit" in response.lower():
                return 1

        return 0


hyperparams = {
    "model_name": "meta-llama/Llama-2-7b-chat-hf",
    "env": "gym_xiangqi:xiangqi-v0",
    "lora/r": 16,
    "lora/lora_alpha": 32,
    "lora/lora_dropout": 0.05,
    "lora/bias": "none",
    "lora/task_type": "CAUSAL_LM",
    # "load_in_8bit": True,
    "batch_size": 8,
    "seed": 42069,
    "episodes": 5000,
    "generate/max_new_tokens": 32,
    "generate/do_sample": True,
    "generate/top_p": 0.6,
    "generate/top_k": 0,
    "generate/temperature": 0.9,
}

device = 'cpu'
HF_TOKEN = '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'


lora_config = LoraConfig(
    **{
        key.split("/")[-1]: value
        for key, value in hyperparams.items()
        if key.startswith("lora/")
    }
)
model = AutoModelForCausalLMWithValueHead.from_pretrained(
    pretrained_model_name_or_path=hyperparams["model_name"],
    peft_config=lora_config,
    # load_in_8bit=hyperparams["load_in_8bit"],
    token=HF_TOKEN,
).to(device)
tokenizer = AutoTokenizer.from_pretrained(hyperparams["model_name"], token=HF_TOKEN)
tokenizer.add_special_tokens({"pad_token": "<pad>"})
model.pretrained_model.resize_token_embeddings(len(tokenizer))

agent = XiangQiAgent(
    model,
    tokenizer,
    device,
    {
        key: value
        for key, value in hyperparams.items()
        if key.startswith("generate/")
    },
    {
        "batch_size": hyperparams["batch_size"],
        "mini_batch_size": hyperparams["batch_size"],
    },
)
env = gym.make(hyperparams["env"], natural=False, sab=False)

for episode in trange(hyperparams["episodes"]):
    observation, info = env.reset()
    done = False

    while not done:
        action = agent.act(observation)
        print(action)
        # wandb.log({"action": action})
        observation, reward, terminated, truncated, info = env.step(action)
        agent.assign_reward(reward)
        done = terminated or truncated

    episode_stats = {
        "episode": episode,
        "total_return": sum(agent.current_episode_rewards),
        "message_ct": len(agent.current_episode_messages),
        "episode_messages": agent.current_episode_messages,
    }
    train_stats = agent.terminate_episode()
    episode_stats.update(train_stats)
    # wandb.log(episode_stats)


In [64]:
class ChineseChessAgent:
    def __init__(
        self,
        learning_rate: float,
        initial_epsilon: float,
        epsilon_decay: float,
        final_epsilon: float,
        discount_factor: float = 0.95,
    ):        
        
        self.q_values = defaultdict(lambda: np.zeros(env.action_space.n))
        self.lr = learning_rate
        self.discount_factor = discount_factor

        self.epsilon = initial_epsilon
        self.epsilon_decay = epsilon_decay
        self.final_epsilon = final_epsilon

        self.training_error = []

    def get_action(self, obs: tuple[int, int, bool]) -> int:
        """
        Returns the best action with probability (1 - epsilon)
        otherwise a random action with probability epsilon to ensure exploration.
        """
        # with probability epsilon return a random action to explore the environment
        if np.random.random() < self.epsilon:
            return env.action_space.sample()

        # with probability (1 - epsilon) act greedily (exploit)
        else:
            return int(np.argmax(self.q_values[obs]))
    def update(
        self,
        obs: tuple[int, int, bool],
        action: int,
        reward: float,
        terminated: bool,
        next_obs: tuple[int, int, bool],
    ):
        """Updates the Q-value of an action."""
        future_q_value = (not terminated) * np.max(self.q_values[next_obs])
        temporal_difference = (
            # NOTE: fill this in
            reward + self.discount_factor * future_q_value - self.q_values[obs][action]
        )

        self.q_values[obs][action] = (
            self.q_values[obs][action] + self.lr * temporal_difference
        )
        self.training_error.append(temporal_difference)

    def decay_epsilon(self):
        self.epsilon = max(self.final_epsilon, self.epsilon - self.epsilon_decay)

In [65]:
learning_rate = 0.01
n_episodes = 100_000
start_epsilon = 1.0
epsilon_decay = start_epsilon / (n_episodes / 2)  # Reduce the exploration over time
final_epsilon = 0.1

agent = ChineseChessAgent(
    learning_rate=learning_rate,
    initial_epsilon=start_epsilon,
    epsilon_decay=epsilon_decay,
    final_epsilon=final_epsilon,
)

In [131]:
class FullyConnectedModel(nn.Module):
    def __init__(self, input_size, output_size):
        super(FullyConnectedModel, self).__init__()

        # Define layers with ReLU activation
        self.linear1 = nn.Linear(input_size, 16)
        self.activation1 = nn.ReLU()
        self.linear2 = nn.Linear(16, 16)
        self.activation2 = nn.ReLU()
        self.linear3 = nn.Linear(16, 16)
        self.activation3 = nn.ReLU()

        # Output layer without activation function
        self.output_layer = nn.Linear(16, output_size)

        # Initialization using Xavier uniform (a popular technique for initializing weights in NNs)
        nn.init.xavier_uniform_(self.linear1.weight)
        nn.init.xavier_uniform_(self.linear2.weight)
        nn.init.xavier_uniform_(self.linear3.weight)
        nn.init.xavier_uniform_(self.output_layer.weight)

    def forward(self, inputs):
        # Forward pass through the layers
        x = self.activation1(self.linear1(inputs))
        x = self.activation2(self.linear2(x))
        x = self.activation3(self.linear3(x))
        x = self.output_layer(x)
        return x

    
class QNetwork:
    def __init__(self, env, lr, logdir=None):
        # Define Q-network with specified architecture
        self.net = FullyConnectedModel(9, 2)
        self.env = env
        self.lr = lr 
        self.logdir = logdir
        self.optimizer = optim.Adam(self.net.parameters(), lr=self.lr)

    def load_model(self, model_file):
        # Load pre-trained model from a file
        return self.net.load_state_dict(torch.load(model_file))

    def load_model_weights(self, weight_file):
        # Load pre-trained model weights from a file
        return self.net.load_state_dict(torch.load(weight_file))


In [132]:
class ReplayMemory:
    def __init__(self, env, memory_size=50000, burn_in=10000):
        # Initializes the replay memory, which stores transitions recorded from the agent taking actions in the environment.
        self.memory_size = memory_size
        self.burn_in = burn_in
        self.memory = collections.deque([], maxlen=memory_size)
        self.env = env

    def sample_batch(self, batch_size=32):
        # Returns a batch of randomly sampled transitions to be used for training the model.
        return random.sample(self.memory, batch_size)

    def append(self, transition):
        # Appends a transition to the replay memory.
        self.memory.append(transition)

In [133]:
env_name = "gym_xiangqi:xiangqi-v0"

In [166]:
from collections import namedtuple

Transition = namedtuple('Transition', ('state', 'action', 'next_state', 'reward'))

class DQN_Agent:

    def __init__(self, environment_name, lr=5e-4, render=False):
        # Initialize the DQN Agent.
        self.env = gym.make(environment_name)
        self.lr = lr
        self.policy_net = QNetwork(self.env, self.lr)
        self.target_net = QNetwork(self.env, self.lr)
        self.target_net.net.load_state_dict(self.policy_net.net.state_dict())  # Copy the weight of the policy network
        self.rm = ReplayMemory(self.env)
        self.burn_in_memory()
        self.batch_size = 32
        self.gamma = 0.99
        self.c = 0

    def burn_in_memory(self):
        # Initialize replay memory with a burn-in number of episodes/transitions.
        cnt = 0
        terminated = False
        truncated = False
        state = self.env.reset()
        state = torch.tensor(state, dtype=torch.float32).unsqueeze(0)

        # Iterate until we store "burn_in" buffer
        while cnt < self.rm.burn_in:
            # Reset environment if terminated or truncated
            if terminated or truncated:
                state = self.env.reset()
                state = torch.tensor(state, dtype=torch.float32).unsqueeze(0)
            
            # Randomly select an action (left or right) and take a step
            action = torch.tensor(random.sample([0, 1], 1)[0]).reshape(1, 1)
            obs, reward, done, info = self.env.step(action.item())
            reward = torch.tensor([reward])
            if terminated:
                next_state = None
            else:
                next_state = torch.tensor(next_state, dtype=torch.float32).unsqueeze(0)
                
            # Store new experience into memory
            transition = Transition(state, action, next_state, reward)
            self.rm.memory.append(transition)
            state = next_state
            cnt += 1

    def epsilon_greedy_policy(self, q_values, epsilon=0.05):
        p = random.random()
        if p > epsilon:
            with torch.no_grad():
                return self.greedy_policy(q_values)
        else:
            return torch.tensor([[self.env.action_space.sample()]], dtype=torch.long)

    def greedy_policy(self, q_values):
        return torch.argmax(q_values)
        
    def train(self):
        # Train the Q-network using Deep Q-learning.
        state = self.env.reset()
        state = torch.tensor(state, dtype=torch.float32).unsqueeze(0)
        done = False

        # Loop until reaching the termination state
        while not done:
            with torch.no_grad():
                q_values = self.policy_net.net(state)

            # Decide the next action with epsilon greedy strategy
            action = self.epsilon_greedy_policy(q_values).reshape(1, 1)
            
            # Take action and observe reward and next state
            obs, reward, done, info = self.env.step(action.item())
            reward = torch.tensor([reward])
            if done:
                next_state = None
            else:
                next_state = torch.tensor(next_state, dtype=torch.float32).unsqueeze(0)

            # Store the new experience
            transition = Transition(state, action, next_state, reward)
            self.rm.memory.append(transition)

            # Move to the next state
            state = next_state

            # Sample minibatch with size N from memory
            transitions = self.rm.sample_batch(self.batch_size)
            batch = Transition(*zip(*transitions))
            non_final_mask = torch.tensor(tuple(map(lambda s: s is not None, batch.next_state)), dtype=torch.bool)
            non_final_next_states = torch.cat([s for s in batch.next_state if s is not None])
            state_batch = torch.cat(batch.state)
            action_batch = torch.cat(batch.action)
            reward_batch = torch.cat(batch.reward)

            # Get current and next state values
            action_batch = action_batch.unsqueeze(1)
            print(action_batch.shape)
            print(state_batch.shape)

            state_action_values = self.policy_net.net(state_batch).gather(1, action_batch) # extract values corresponding to the actions Q(S_t, A_t)
            next_state_values = torch.zeros(self.batch_size)
            
            print(next_state_values.shape)
            with torch.no_grad():
                # no next_state_value update if an episode is terminated (next_satate = None)
                # only update the non-termination state values (Ref: https://gymnasium.farama.org/tutorials/gymnasium_basics/handling_time_limits/)
                print(non_final_next_states)
                next_state_values[non_final_mask] = self.target_net.net(non_final_next_states).max(1)[0] # extract max value
                
            # Update the model
            expected_state_action_values = (next_state_values * self.gamma) + reward_batch
            criterion = torch.nn.MSELoss()
            loss = criterion(state_action_values, expected_state_action_values.unsqueeze(1))
            self.policy_net.optimizer.zero_grad()
            loss.backward()
            self.policy_net.optimizer.step()

            # Update the target Q-network in each 50 steps
            self.c += 1
            if self.c % 50 == 0:
                self.target_net.net.load_state_dict(self.policy_net.net.state_dict())

    def test(self, model_file=None):
        # Evaluates the performance of the agent over 20 episodes.

        max_t = 1000
        state = self.env.reset()
        rewards = []

        for t in range(max_t):
            state = torch.from_numpy(state).float().unsqueeze(0)
            with torch.no_grad():
                q_values = self.policy_net.net(state)
            action = self.greedy_policy(q_values)
            obs, reward, done, info = self.env.step(action.item())
            rewards.append(reward)
            if done:
                break

        return np.sum(rewards)

In [167]:
import matplotlib as plt
import torch.optim as optim


In [168]:
num_episodes_train = 200
num_episodes_test = 20
learning_rate = 5e-4

# Create the environment
env = gym.make(env_name)
action_space_size = env.action_space.n
state_space_size = 4

# Plot average performance of 5 trials
num_seeds = 5
l = num_episodes_train // 10
res = np.zeros((num_seeds, l))
gamma = 0.99

# Loop over multiple seeds
for i in tqdm(range(num_seeds)):
    reward_means = []

    # Create an instance of the DQN_Agent class
    agent = DQN_Agent(env_name, lr=learning_rate)

    # Training loop
    for m in range(num_episodes_train):
        agent.train()

        # Evaluate the agent every 10 episodes during training
        if m % 10 == 0:
            print("Episode: {}".format(m))

            # Evaluate the agent's performance over 20 test episodes
            G = np.zeros(num_episodes_test)
            for k in range(num_episodes_test):
                g = agent.test()
                G[k] = g

            reward_mean = G.mean()
            reward_sd = G.std()
            print(f"The test reward for episode {m} is {reward_mean} with a standard deviation of {reward_sd}.")
            reward_means.append(reward_mean)

    res[i] = np.array(reward_means)

# Plotting the average performance
ks = np.arange(l) * 10
avs = np.mean(res, axis=0)
maxs = np.max(res, axis=0)
mins = np.min(res, axis=0)

plt.fill_between(ks, mins, maxs, alpha=0.1)
plt.plot(ks, avs, '-o', markersize=1)

plt.xlabel('Episode', fontsize=15)
plt.ylabel('Avg. Return', fontsize=15)

  0%|          | 0/5 [00:01<?, ?it/s]

torch.Size([32, 1, 1])
torch.Size([32, 10, 9])
torch.Size([32])
tensor([[[ -9.,  -7.,  -5.,  ...,  -4.,  -6.,  -8.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0., -11.,   0.,  ...,   0., -10.,   0.],
         ...,
         [  0.,  10.,   0.,  ...,   0.,  11.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  8.,   6.,   4.,  ...,   5.,   7.,   9.]],

        [[ -9.,  -7.,  -5.,  ...,  -4.,  -6.,  -8.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0., -11.,   0.,  ...,   0., -10.,   0.],
         ...,
         [  0.,  10.,   0.,  ...,   0.,  11.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  8.,   6.,   4.,  ...,   5.,   7.,   9.]],

        [[ -9.,  -7.,  -5.,  ...,  -4.,  -6.,  -8.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0., -11.,   0.,  ...,   0., -10.,   0.],
         ...,
         [  0.,  10.,   0.,  ...,   0.,  11.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   

RuntimeError: shape mismatch: value tensor of shape [32, 2] cannot be broadcast to indexing result of shape [32]